#! /bin/sh
# mlc: Merge LaTeX Container

if [ -d .devcontainer ]; then
  echo already merged
  exit
fi

case $(uname -m) in
    x86_64)
      branch=alpine
      ;;
    *)
      branch=latest
      ;;
esac

mkdir .tmp
git mv .gitignore .latexmkrc .textlintrc .tmp
git commit -m "mv files temporary to avoid conflict"

echo merge LaTeX environment
git remote add latexenv https://github.com/smkwlab/latex-environment.git
git fetch latexenv
git merge --allow-unrelated-histories -m "merge latex environment" latexenv/${branch}
git remote remove latexenv

git rm -r .gitignore .latexmkrc .textlintrc
git mv .tmp/.gitignore .tmp/.latexmkrc .tmp/.textlintrc .
rmdir .tmp

git commit -m "update .gitignore & .textlintrc"
git push
