on:
  pull_request_target:

env:
  FILENAME: sotsuron
jobs:
  release:
    runs-on: ubuntu-latest
    container: ghcr.io/smkwlab/latex-docker
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          ref: draft
      - name: Build a PDF file by latexmk
        run: latexmk $FILENAME.tex
      - name: Create Git Tag
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git tag ${{ github.event.pull_request.title }}
          git push origin ${{ github.event.pull_request.title }}
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.FILENAME }}.pdf
          tag_name: ${{ github.event.pull_request.title }}
          release_name: ${{ github.event.pull_request.title }}
          draft: true
          prerelease: true
