name: Build and Release PDF

on:
  pull_request_target:

permissions:
  contents: write

jobs:
  sotsuron:
    uses: ./.github/workflows/build-and-release.yml
    with:
      file: sotsuron

  gaiyou:
    uses: ./.github/workflows/build-and-release.yml
    with:
      file: gaiyou
