name: Build and Release PDF

on:
  pull_request_target:

permissions:
  contents: write

env:
  FILENAME: sotsuron
  FILENAME2: gaiyou

jobs:
  release:
    runs-on: ubuntu-latest
    container: ghcr.io/smkwlab/latex-image
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build a PDF file by latexmk
        run: latexmk $FILENAME $FILENAME2
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ env.FILENAME }}.pdf
            ${{ env.FILENAME2 }}.pdf
          tag_name: ${{ github.head_ref }}-release
          draft: false
          prerelease: true
