name: Build and Release PDF

on:
  pull_request_target:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container: ghcr.io/smkwlab/alpine-texlive-ja-textlint:latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: build sotsuron.pdf
        uses: ./.github/workflows/build-and-release.yml
        with:
          file: sotsuron

      - name: build gaiyou.pdf
        uses: ./.github/workflows/build-and-release.yml
        with:
          file: gaiyou
